# Generated by Django 2.2.1 on 2019-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_applicant_completed_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laborer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='apply/laborer/resume')),
                ('completed_application', models.FileField(upload_to='apply/laborer/application')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='apply/operator/resume')),
                ('completed_application', models.FileField(upload_to='apply/operator/application')),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
