# Generated by Django 2.2.1 on 2019-07-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20190706_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='laborer',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
